# ????????
server.port=8080

spring.datasource.url=jdbc:hive2://192.168.220.151:10000/vehicle_db
spring.datasource.driver-class-name=org.apache.hive.jdbc.HiveDriver
spring.datasource.username=hadoop
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=5


mybatis.configuration.map-underscore-to-camel-case=true

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.vehicle.pojo

hadoop.conf.path=D:/hadoop-3.3.4/etc/hadoop
hdfs.uri=hdfs://192.168.220.151:8020
hdfs.input.path=/user/hive/warehouse/bike_stats
hdfs.output.path=/user/hive/warehouse/bike_stats_output